version: '3.3'

services:
  core:
    container_name: openhim-core
    image: jembi/openhim-core:5
    environment:
      - mongo_url=mongodb://mongo-1:27017,mongo-2:27017,mongo-3:27017/openhim?replicaSet=mongo-set
      - mongo_atnaUrl=mongodb://mongo-1:27017,mongo-2:27017,mongo-3:27017/openhim?replicaSet=mongo-set
      - api_authenticationTypes=["token", "basic"]
      - authentication_enableCustomTokenAuthentication=true
    ports:
#      - "5000:5000"
      - "5001:5001"
      - "5050:5050"
      - "5052:5052"

  # this service exposed via nginx_proxy
  console:
    container_name: openhim-console
    image: jembi/openhim-console:1.14

  fhir:
    container_name: hapi-fhir
    image: hapiproject/hapi:v5.2.1
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/hapi
      - spring.datasource.username=admin
      - spring.datasource.password=instant101
      - spring.datasource.driverClassName=com.mysql.jdbc.Driver
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
      - hapi.fhir.allow_external_references=true
    volumes:
      - type: volume
        source: instant
        target: /instant
    depends_on:
      - mysql

  mysql:
    container_name: hapi-mysql
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_DATABASE: 'hapi'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'instant101'
      MYSQL_ROOT_PASSWORD: 'instant101'
    volumes:
      - 'hapi-mysql:/var/lib/mysql'

  diym:
    container_name: diym
    build: ../DIYM/.
    volumes:
      - ../DIYM/config:/etc/diym

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    depends_on:
      - fhir
      - core
      - console
      - diym
    ports:
      - 8080:8080
      - 9001:9001
      - 5002:5002
      - 5003:5003

volumes:
  hapi-mysql:
  instant:
    external: true

