# https://test:test@192-168-68-108.my.local-ip.co:5002
# https://medic:password@192-168-68-108.my.local-ip.co

default:
  diym_credentials:
    - login: "test"
      password: "test"

    - login: "test2"
      password: "test2"

  openhim:
    user: "test"
    password: "test"
    url: "192-168-68-108.my.local-ip.co"
    port: 5002
    transport: "https"

  chw_systems:
    - item: cht
      user: "medic"
      password: "password"
      url: "192-168-68-108.my.local-ip.co"
      port: 5002
      transport: "https"
    - item: commcare
      user: "test"
      password: "test"
      url: "192-168-68-108.my.local-ip.co"
      port: 5002
      transport: "https"
    - item: opensrp
      user: "test"
      password: "test"
      url: "192-168-68-108.my.local-ip.co"
      port: 5002
      transport: "https"